### ISSUE TITLE
GenericJodaSupport Slick 3.0 play-slick 1.0.0 README example not working

### ISSUE THREAD

**Issue by xevix** [tototoshi/slick-joda-mapper#33]
Per the README, you can create your own agnostic adapter for play-slick via:

`object PortableJodaSupport extends com.github.tototoshi.slick.GenericJodaSupport(play.api.db.slick.Config.driver)`

However, that no longer seems to exist. Specifically, `play.api.db.slick.Config` doesn't seem to exist. Perhaps this needs an update? I can't seem to find where this has moved.

Thanks!

**Comment by adheus** [comment]
Same problem here.. Any fixes?

**Comment by gavares** [comment]
+1

**Comment by adheus** [comment]
As a workaround, since we waiting these to get done(not rushing anyone here). I replaced my PortableJodaSlickSupport class with a custom class: 

import java.sql.Timestamp

import org.joda.time.DateTime
import play.api.Play
import play.api.db.slick.{HasDatabaseConfig, DatabaseConfigProvider}
import slick.driver.JdbcProfile

object PortableJodaSlickSupport  extends HasDatabaseConfig[JdbcProfile] {
  protected val dbConfig = DatabaseConfigProvider.get[JdbcProfile](Play.current)

  import driver.api._
  implicit val timestamp2dateTime =  MappedColumnType.base[DateTime, Timestamp] (
    dateTime => new Timestamp(dateTime.getMillis),
    timestamp => new DateTime(timestamp)
  )

}

**I'm using play-slick 1.0.x with Slick 3.0.x

**Comment by tototoshi** [comment]
Removed the part about play-slick from README.md.
